### PR TITLE
Fixed bug of DiscreteMIP lax/tight precedence constraints

### PR DESCRIPTION
**Pull request by crayster**
Please refer to the comment on commit.

### CODE REVIEW

**Comment by timnon** [comment]
Just checked, precedence constraints between groups of different size dont seem to work. This is the problem, right? In the example above replacing the size of group2 to 5 gives a valid solution.

However, this should also work for groups of different size. The root cause is that the constraint implementation

```python
affine = [(x[P.task_left, t_],1) for t_ in range(t,self.horizon)] + \
       [(x[P.task_right, t_],-1) for t_ in range(min(t+P.task_left.length+P.offset,self.horizon),self.horizon)]
cons.append(mip.con(affine, sense=-1, rhs=0))
```

does not take different groups sizes into account, but I think it is possible to fix this by simply adding the difference in groups sizes to one of the sides of the constraint. I will check and test this on the weekend. This would not require additional variables which increase the solving time.

Thanks for pointing out this problem! If I will not be able to fix it this way I would merge the pull request.

**Comment by crayster** [comment]
> This is the problem, right? In the example above replacing the size of group2 to 5 gives a valid solution.

Hmm... I'm not sure. In my opinion, even replace the size of group2 to 5, the answer seems not right either.
For example,
```python
# output of "S += S['T2_0'] < S['T1_0']"
[(T2_0, R2, 0, 3), (T1_0, R1, 3, 5), (T2_1, R2, 3, 6), (T1_1, R1, 6, 8), (T2_2, R2, 6, 9), (T1_2, R1, 9, 11), (T2_3, R2, 9, 12), (T1_3, R1, 12, 14), (T2_4, R2, 12, 15), (T1_4, R1, 15, 17)]
```
Except the head tasks (T1_0, T2_0), the others remain in random order (My expected order is T2_0, T2_1,.... T2_4, T1_0, ... T1_4).

And because this statement:
```python
if P.task_left not in self.task_groups or P.task_right not in self.task_groups:
	continue
```
I can't control the orders of them...
Perhaps it's my misunderstanding of the usage. Hope you can clarify, that's also why I posted this request. Thank you!

**Comment by crayster** [comment]
In addition, I just changed the action of up bound, tight up/low bound a little.
Mainly two points:
1. At least for my case, "T < x" means T must finish before x, so T.length should be considered.
2. For tight bound,
`mip.con([(x[P.task, P.bound],1)], sense=0, rhs=task_group_size)`
makes all tasks start exactly at P.bound... not very fit for my case.

**Comment by timnon** [comment]
First, regarding the ordering in
`
[(T2_0, R2, 0, 3), (T1_0, R1, 3, 5), (T2_1, R2, 3, 6), (T1_1, R1, 6, 8), (T2_2, R2, 6, 9), (T1_2, R1, 9, 11), (T2_3, R2, 9, 12), (T1_3, R1, 12, 14), (T2_4, R2, 12, 15), (T1_4, R1, 15, 17)]
`
This looks correct. To clarify the usage of precedence relations in groups, `T2_0 < T1_0` implies that `group2` should be before `group1`. This means that the first task in `group2` should be before the first task in `group1`, the second task in `group2` should be before the second task in `group1`, etc. 

A scenario for this would be the production of some product which requires two tasks, first on one machine, and then on a second. So the xth task on the first machine should be before the xth task on the second machine...

The output above does that `T1_0` starts at time step 3 after `T2_0` finishes,`T1_1` starts after time step 6 after `T2_1` finishes, and so on. It is much easier to show this on a picture with `plotters.matplotlib.plot`, but it is not possible to include pictures here.

Does this make sense?

For the two machine use case described above, both groups need to have tha same size, in which case everything runs nicely. I spend some thinking what to do for different sized groups. Then it is not clear what is the best default, there are different options that make sense.

**Comment by timnon** [comment]
Second, regarding the bounds:

1) Yes, you are correct, there is a bug in the upper bound (`T<0`), the `T.length` is missing. Thanks. In your commit, are you sure about the `+1` in `affine = [(x[P.task, t],1) for t in range(P.bound-P.task.length+1,self.horizon)]`? Also, it should be `range(max(P.bound-P.task.length,0),self.horizon)` to avoid going to negative periods.

2) Regarding the tight bounds (`T<=x` and `T>=x`). For groups, a tight bound `T>=x` would imply that all tasks in the group of task `T` should start in exactly period `x`. Your change
```python
affine = [(x[P.task, t],1) for t in range(P.bound)]
cons.append(mip.con(affine, sense=0, rhs=0))
cons.append(mip.con([(x[P.task, P.bound],1)], sense=1, rhs=1))
```
would imply that at least one task in the group of task `T` should start in exactly period `x`. Now comes the question which makes more sense? I would probably go for your option, because the current "all" option can be implemented by also adding an upper bound, but the "one" option cannot.

After checking the `+1` and the range problem, could you please create a pull request just for the bounds, i would then merge this in right away.

**Comment by crayster** [comment]
Thanks for your valuable explanations.

> This looks correct. To clarify the usage of precedence relations in groups, T2_0 < T1_0 implies that group2 should be before group1. This means that the first task in group2 should be before the first task in group1, the second task in group2 should be before the second task in group1, etc. 

OK, I see. Hmm, in my case perhaps different size is more common... anyway, I'll consider how to make use of this "group", or create another one.
And also about tight bounds, perhaps the "one" option makes more sense for me ...
Maybe, supplying options to users will be a good idea.

Very interesting discussion, thank you again.

**Comment by crayster** [comment]
After checking, I'm sure +1 should be necessary for up bounds...

**Pull request merged**
